export declare const iconNames: readonly [
  "icon-plus",
  "icon-filter",
  "icon-download",
  "icon-check",
  "icon-x",
  "icon-refresh",
  "icon-more",
  "icon-search",
  "icon-calendar",
  "icon-user",
  "icon-file",
  "icon-table",
  "icon-alert",
  "icon-settings",
  "icon-lock",
  "icon-sun",
  "icon-moon",
  "icon-chevron-down",
  "icon-chevron-up",
  "icon-chevron-left",
  "icon-chevron-right",
  "icon-arrow-up",
  "icon-arrow-down",
  "icon-info",
  "icon-check-circle",
  "icon-edit",
  "icon-trash",
  "icon-paperclip",
  "icon-bell",
  "icon-upload",
  "icon-link",
  "icon-external-link",
  "icon-eye",
  "icon-eye-off",
  "icon-clock",
  "icon-help",
  "icon-menu",
  "icon-mail",
  "icon-image",
  "icon-folder",
  "icon-tag",
  "icon-star",
  "icon-grid",
  "icon-list",
  "icon-warning",
];

export type IconName = (typeof iconNames)[number];

export declare const iconSpriteHref = "@idenflu/ui-icons/icons.svg";

export declare const getIconHref: (name: IconName, spriteHref?: string) => string;
