export const iconNames = [
  "add",
  "arrow-down",
  "arrow-up",
  "arrow-left",
  "arrow-right",
  "attach",
  "calendar",
  "check",
  "check-circle",
  "close",
  "clock",
  "crop",
  "dark-mode",
  "delete",
  "download",
  "edit",
  "expand",
  "file",
  "folder",
  "filter",
  "grid",
  "help",
  "image",
  "info",
  "link",
  "list",
  "lock",
  "mail",
  "menu",
  "more-horizontal",
  "more-vertical",
  "keyboard-arrow-down",
  "keyboard-arrow-up",
  "keyboard-arrow-left",
  "keyboard-arrow-right",
  "person",
  "play",
  "play-disabled",
  "restart",
  "remove",
  "search",
  "star",
  "swap",
  "text",
  "tree",
  "visibility",
  "visibility-off",
  "upload",
  "warning",
  "table",
] as const;

export type IconName = (typeof iconNames)[number];

export const iconSpriteHref = "@idenflu/ui-icons/icons.svg";

export const getIconHref = (name: IconName, spriteHref = iconSpriteHref) =>
  `${spriteHref}#${name}`;
